name: Google OSV Scheduled Scan

on:
  schedule:
    - cron: "30 2 15,30 * *"
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.4
        with:
          scan-args: |-
            --results-file-name=osv-results.sarif
            --upload-sarif:true

