name: 03.Docker Scout CVE Scan

on:
  schedule:
    - cron: "15 2 * * SUN"
  workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=skip=SecretsUsedInArgOrEnv

      - name: Docker Scout CVEs
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest
          only-severities: critical,high
          only-fixed: true
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exit-code: true
          sarif-file: docker-scout-report.sarif
      - name: Upload Docker Scout SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'docker-scout-report.sarif'
